//
//  Pokemon.swift
//  pokedex
//
//  Created by Magnus Jensen on 12/08/2021.
//

import Foundation

extension Pokemon: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

extension Pokemon: Equatable {
    public static func == (lhs: Pokemon, rhs: Pokemon) -> Bool {
        lhs.id == rhs.id
    }
}

public struct Pokemon: Identifiable {
    public let id = UUID()
    public let number: String
    public let name: String
    public let image: URL
    public let type: [PokemonType]
    public let height: String
    public let weight: String
    public let weaknesses: [PokemonType]
    fileprivate let next_evolution: [PokemonReference]?
    fileprivate let prev_evolution: [PokemonReference]?
    
    public var related: [Pokemon]? {
        let references = [prev_evolution, next_evolution]
            .compactMap { $0 }
            .flatMap { $0 }
        guard !references.isEmpty else {
            return nil
        }
        return references.compactMap { ref in
            pokemons.first { ref.number == $0.number }
        }
    }
    
}

public struct PokemonReference: Identifiable {
    public let id = UUID()
    public let number: String
    public let name: String
}

public enum PokemonType: String, Codable {
    case fire, ice, flying, psychic, grass, poison, water, bug, normal, electric, ground, fighting, rock, ghost, dragon, fairy, dark, steel
}

public let pokemons = [
Pokemon(number: "001", name: "Bulbasaur", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/001.png")!, type: [.grass, .poison], height: "0.71 m", weight: "6.9 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "002", name: "Ivysaur"), PokemonReference(number: "003", name: "Venusaur")], prev_evolution: nil),
Pokemon(number: "002", name: "Ivysaur", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/002.png")!, type: [.grass, .poison], height: "0.99 m", weight: "13.0 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "003", name: "Venusaur")], prev_evolution: [PokemonReference(number: "001", name: "Bulbasaur")]),
Pokemon(number: "003", name: "Venusaur", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/003.png")!, type: [.grass, .poison], height: "2.01 m", weight: "100.0 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "001", name: "Bulbasaur"), PokemonReference(number: "002", name: "Ivysaur")]),
Pokemon(number: "004", name: "Charmander", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/004.png")!, type: [.fire], height: "0.61 m", weight: "8.5 kg", weaknesses: [.water, .ground, .rock], next_evolution: [PokemonReference(number: "005", name: "Charmeleon"), PokemonReference(number: "006", name: "Charizard")], prev_evolution: nil),
Pokemon(number: "005", name: "Charmeleon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/005.png")!, type: [.fire], height: "1.09 m", weight: "19.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: [PokemonReference(number: "006", name: "Charizard")], prev_evolution: [PokemonReference(number: "004", name: "Charmander")]),
Pokemon(number: "006", name: "Charizard", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/006.png")!, type: [.fire, .flying], height: "1.70 m", weight: "90.5 kg", weaknesses: [.water, .electric, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "004", name: "Charmander"), PokemonReference(number: "005", name: "Charmeleon")]),
Pokemon(number: "007", name: "Squirtle", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/007.png")!, type: [.water], height: "0.51 m", weight: "9.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "008", name: "Wartortle"), PokemonReference(number: "009", name: "Blastoise")], prev_evolution: nil),
Pokemon(number: "008", name: "Wartortle", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/008.png")!, type: [.water], height: "0.99 m", weight: "22.5 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "009", name: "Blastoise")], prev_evolution: [PokemonReference(number: "007", name: "Squirtle")]),
Pokemon(number: "009", name: "Blastoise", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/009.png")!, type: [.water], height: "1.60 m", weight: "85.5 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "007", name: "Squirtle"), PokemonReference(number: "008", name: "Wartortle")]),
Pokemon(number: "010", name: "Caterpie", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/010.png")!, type: [.bug], height: "0.30 m", weight: "2.9 kg", weaknesses: [.fire, .flying, .rock], next_evolution: [PokemonReference(number: "011", name: "Metapod"), PokemonReference(number: "012", name: "Butterfree")], prev_evolution: nil),
Pokemon(number: "011", name: "Metapod", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/011.png")!, type: [.bug], height: "0.71 m", weight: "9.9 kg", weaknesses: [.fire, .flying, .rock], next_evolution: [PokemonReference(number: "012", name: "Butterfree")], prev_evolution: [PokemonReference(number: "010", name: "Caterpie")]),
Pokemon(number: "012", name: "Butterfree", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/012.png")!, type: [.bug, .flying], height: "1.09 m", weight: "32.0 kg", weaknesses: [.fire, .electric, .ice, .flying, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "010", name: "Caterpie"), PokemonReference(number: "011", name: "Metapod")]),
Pokemon(number: "013", name: "Weedle", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/013.png")!, type: [.bug, .poison], height: "0.30 m", weight: "3.2 kg", weaknesses: [.fire, .flying, .psychic, .rock], next_evolution: [PokemonReference(number: "014", name: "Kakuna"), PokemonReference(number: "015", name: "Beedrill")], prev_evolution: nil),
Pokemon(number: "014", name: "Kakuna", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/014.png")!, type: [.bug, .poison], height: "0.61 m", weight: "10.0 kg", weaknesses: [.fire, .flying, .psychic, .rock], next_evolution: [PokemonReference(number: "015", name: "Beedrill")], prev_evolution: [PokemonReference(number: "013", name: "Weedle")]),
Pokemon(number: "015", name: "Beedrill", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/015.png")!, type: [.bug, .poison], height: "0.99 m", weight: "29.5 kg", weaknesses: [.fire, .flying, .psychic, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "013", name: "Weedle"), PokemonReference(number: "014", name: "Kakuna")]),
Pokemon(number: "016", name: "Pidgey", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/016.png")!, type: [.normal, .flying], height: "0.30 m", weight: "1.8 kg", weaknesses: [.electric, .rock], next_evolution: [PokemonReference(number: "017", name: "Pidgeotto"), PokemonReference(number: "018", name: "Pidgeot")], prev_evolution: nil),
Pokemon(number: "017", name: "Pidgeotto", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/017.png")!, type: [.normal, .flying], height: "1.09 m", weight: "30.0 kg", weaknesses: [.electric, .rock], next_evolution: [PokemonReference(number: "018", name: "Pidgeot")], prev_evolution: [PokemonReference(number: "016", name: "Pidgey")]),
Pokemon(number: "018", name: "Pidgeot", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/018.png")!, type: [.normal, .flying], height: "1.50 m", weight: "39.5 kg", weaknesses: [.electric, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "016", name: "Pidgey"), PokemonReference(number: "017", name: "Pidgeotto")]),
Pokemon(number: "019", name: "Rattata", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/019.png")!, type: [.normal], height: "0.30 m", weight: "3.5 kg", weaknesses: [.fighting], next_evolution: [PokemonReference(number: "020", name: "Raticate")], prev_evolution: nil),
Pokemon(number: "020", name: "Raticate", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/020.png")!, type: [.normal], height: "0.71 m", weight: "18.5 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: [PokemonReference(number: "019", name: "Rattata")]),
Pokemon(number: "021", name: "Spearow", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/021.png")!, type: [.normal, .flying], height: "0.30 m", weight: "2.0 kg", weaknesses: [.electric, .rock], next_evolution: [PokemonReference(number: "022", name: "Fearow")], prev_evolution: nil),
Pokemon(number: "022", name: "Fearow", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/022.png")!, type: [.normal, .flying], height: "1.19 m", weight: "38.0 kg", weaknesses: [.electric, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "021", name: "Spearow")]),
Pokemon(number: "023", name: "Ekans", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/023.png")!, type: [.poison], height: "2.01 m", weight: "6.9 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "024", name: "Arbok")], prev_evolution: nil),
Pokemon(number: "024", name: "Arbok", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/024.png")!, type: [.poison], height: "3.51 m", weight: "65.0 kg", weaknesses: [.ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "023", name: "Ekans")]),
Pokemon(number: "025", name: "Pikachu", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/025.png")!, type: [.electric], height: "0.41 m", weight: "6.0 kg", weaknesses: [.ground], next_evolution: [PokemonReference(number: "026", name: "Raichu")], prev_evolution: nil),
Pokemon(number: "026", name: "Raichu", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/026.png")!, type: [.electric], height: "0.79 m", weight: "30.0 kg", weaknesses: [.ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "025", name: "Pikachu")]),
Pokemon(number: "027", name: "Sandshrew", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/027.png")!, type: [.ground], height: "0.61 m", weight: "12.0 kg", weaknesses: [.water, .grass, .ice], next_evolution: [PokemonReference(number: "028", name: "Sandslash")], prev_evolution: nil),
Pokemon(number: "028", name: "Sandslash", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/028.png")!, type: [.ground], height: "0.99 m", weight: "29.5 kg", weaknesses: [.water, .grass, .ice], next_evolution: nil, prev_evolution: [PokemonReference(number: "027", name: "Sandshrew")]),
Pokemon(number: "029", name: "Nidoran (Female)", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/029.png")!, type: [.poison], height: "0.41 m", weight: "7.0 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "030", name: "Nidorina"), PokemonReference(number: "031", name: "Nidoqueen")], prev_evolution: nil),
Pokemon(number: "030", name: "Nidorina", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/030.png")!, type: [.poison], height: "0.79 m", weight: "20.0 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "031", name: "Nidoqueen")], prev_evolution: [PokemonReference(number: "029", name: "Nidoran(Female)")]),
Pokemon(number: "031", name: "Nidoqueen", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/031.png")!, type: [.poison, .ground], height: "1.30 m", weight: "60.0 kg", weaknesses: [.water, .ice, .ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "029", name: "Nidoran(Female)"), PokemonReference(number: "030", name: "Nidorina")]),
Pokemon(number: "032", name: "Nidoran (Male)", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/032.png")!, type: [.poison], height: "0.51 m", weight: "9.0 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "033", name: "Nidorino"), PokemonReference(number: "034", name: "Nidoking")], prev_evolution: nil),
Pokemon(number: "033", name: "Nidorino", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/033.png")!, type: [.poison], height: "0.89 m", weight: "19.5 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "034", name: "Nidoking")], prev_evolution: [PokemonReference(number: "032", name: "Nidoran(Male)")]),
Pokemon(number: "034", name: "Nidoking", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/034.png")!, type: [.poison, .ground], height: "1.40 m", weight: "62.0 kg", weaknesses: [.water, .ice, .ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "032", name: "Nidoran(Male)"), PokemonReference(number: "033", name: "Nidorino")]),
Pokemon(number: "035", name: "Clefairy", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/035.png")!, type: [.normal], height: "0.61 m", weight: "7.5 kg", weaknesses: [.fighting], next_evolution: [PokemonReference(number: "036", name: "Clefable")], prev_evolution: nil),
Pokemon(number: "036", name: "Clefable", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/036.png")!, type: [.normal], height: "1.30 m", weight: "40.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: [PokemonReference(number: "035", name: "Clefairy")]),
Pokemon(number: "037", name: "Vulpix", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/037.png")!, type: [.fire], height: "0.61 m", weight: "9.9 kg", weaknesses: [.water, .ground, .rock], next_evolution: [PokemonReference(number: "038", name: "Ninetales")], prev_evolution: nil),
Pokemon(number: "038", name: "Ninetales", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/038.png")!, type: [.fire], height: "1.09 m", weight: "19.9 kg", weaknesses: [.water, .ground, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "037", name: "Vulpix")]),
Pokemon(number: "039", name: "Jigglypuff", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/039.png")!, type: [.normal], height: "0.51 m", weight: "5.5 kg", weaknesses: [.fighting], next_evolution: [PokemonReference(number: "040", name: "Wigglytuff")], prev_evolution: nil),
Pokemon(number: "040", name: "Wigglytuff", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/040.png")!, type: [.normal], height: "0.99 m", weight: "12.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: [PokemonReference(number: "039", name: "Jigglypuff")]),
Pokemon(number: "041", name: "Zubat", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/041.png")!, type: [.poison, .flying], height: "0.79 m", weight: "7.5 kg", weaknesses: [.electric, .ice, .psychic, .rock], next_evolution: [PokemonReference(number: "042", name: "Golbat")], prev_evolution: nil),
Pokemon(number: "042", name: "Golbat", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/042.png")!, type: [.poison, .flying], height: "1.60 m", weight: "55.0 kg", weaknesses: [.electric, .ice, .psychic, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "041", name: "Zubat")]),
Pokemon(number: "043", name: "Oddish", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/043.png")!, type: [.grass, .poison], height: "0.51 m", weight: "5.4 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "044", name: "Gloom"), PokemonReference(number: "045", name: "Vileplume")], prev_evolution: nil),
Pokemon(number: "044", name: "Gloom", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/044.png")!, type: [.grass, .poison], height: "0.79 m", weight: "8.6 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "045", name: "Vileplume")], prev_evolution: [PokemonReference(number: "043", name: "Oddish")]),
Pokemon(number: "045", name: "Vileplume", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/045.png")!, type: [.grass, .poison], height: "1.19 m", weight: "18.6 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "043", name: "Oddish"), PokemonReference(number: "044", name: "Gloom")]),
Pokemon(number: "046", name: "Paras", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/046.png")!, type: [.bug, .grass], height: "0.30 m", weight: "5.4 kg", weaknesses: [.fire, .ice, .poison, .flying, .bug, .rock], next_evolution: [PokemonReference(number: "047", name: "Parasect")], prev_evolution: nil),
Pokemon(number: "047", name: "Parasect", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/047.png")!, type: [.bug, .grass], height: "0.99 m", weight: "29.5 kg", weaknesses: [.fire, .ice, .poison, .flying, .bug, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "046", name: "Paras")]),
Pokemon(number: "048", name: "Venonat", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/048.png")!, type: [.bug, .poison], height: "0.99 m", weight: "30.0 kg", weaknesses: [.fire, .flying, .psychic, .rock], next_evolution: [PokemonReference(number: "049", name: "Venomoth")], prev_evolution: nil),
Pokemon(number: "049", name: "Venomoth", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/049.png")!, type: [.bug, .poison], height: "1.50 m", weight: "12.5 kg", weaknesses: [.fire, .flying, .psychic, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "048", name: "Venonat")]),
Pokemon(number: "050", name: "Diglett", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/050.png")!, type: [.ground], height: "0.20 m", weight: "0.8 kg", weaknesses: [.water, .grass, .ice], next_evolution: [PokemonReference(number: "051", name: "Dugtrio")], prev_evolution: nil),
Pokemon(number: "051", name: "Dugtrio", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/051.png")!, type: [.ground], height: "0.71 m", weight: "33.3 kg", weaknesses: [.water, .grass, .ice], next_evolution: nil, prev_evolution: [PokemonReference(number: "050", name: "Diglett")]),
Pokemon(number: "052", name: "Meowth", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/052.png")!, type: [.normal], height: "0.41 m", weight: "4.2 kg", weaknesses: [.fighting], next_evolution: [PokemonReference(number: "053", name: "Persian")], prev_evolution: nil),
Pokemon(number: "053", name: "Persian", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/053.png")!, type: [.normal], height: "0.99 m", weight: "32.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: [PokemonReference(number: "052", name: "Meowth")]),
Pokemon(number: "054", name: "Psyduck", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/054.png")!, type: [.water], height: "0.79 m", weight: "19.6 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "055", name: "Golduck")], prev_evolution: nil),
Pokemon(number: "055", name: "Golduck", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/055.png")!, type: [.water], height: "1.70 m", weight: "76.6 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "054", name: "Psyduck")]),
Pokemon(number: "056", name: "Mankey", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/056.png")!, type: [.fighting], height: "0.51 m", weight: "28.0 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: [PokemonReference(number: "057", name: "Primeape")], prev_evolution: nil),
Pokemon(number: "057", name: "Primeape", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/057.png")!, type: [.fighting], height: "0.99 m", weight: "32.0 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: nil, prev_evolution: [PokemonReference(number: "056", name: "Mankey")]),
Pokemon(number: "058", name: "Growlithe", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/058.png")!, type: [.fire], height: "0.71 m", weight: "19.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: [PokemonReference(number: "059", name: "Arcanine")], prev_evolution: nil),
Pokemon(number: "059", name: "Arcanine", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/059.png")!, type: [.fire], height: "1.91 m", weight: "155.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "058", name: "Growlithe")]),
Pokemon(number: "060", name: "Poliwag", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/060.png")!, type: [.water], height: "0.61 m", weight: "12.4 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "061", name: "Poliwhirl"), PokemonReference(number: "062", name: "Poliwrath")], prev_evolution: nil),
Pokemon(number: "061", name: "Poliwhirl", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/061.png")!, type: [.water], height: "0.99 m", weight: "20.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "062", name: "Poliwrath")], prev_evolution: [PokemonReference(number: "060", name: "Poliwag")]),
Pokemon(number: "062", name: "Poliwrath", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/062.png")!, type: [.water, .fighting], height: "1.30 m", weight: "54.0 kg", weaknesses: [.electric, .grass, .flying, .psychic, .fairy], next_evolution: nil, prev_evolution: [PokemonReference(number: "060", name: "Poliwag"), PokemonReference(number: "061", name: "Poliwhirl")]),
Pokemon(number: "063", name: "Abra", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/063.png")!, type: [.psychic], height: "0.89 m", weight: "19.5 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: [PokemonReference(number: "064", name: "Kadabra"), PokemonReference(number: "065", name: "Alakazam")], prev_evolution: nil),
Pokemon(number: "064", name: "Kadabra", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/064.png")!, type: [.psychic], height: "1.30 m", weight: "56.5 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: [PokemonReference(number: "065", name: "Alakazam")], prev_evolution: [PokemonReference(number: "063", name: "Abra")]),
Pokemon(number: "065", name: "Alakazam", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/065.png")!, type: [.psychic], height: "1.50 m", weight: "48.0 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "063", name: "Abra"), PokemonReference(number: "064", name: "Kadabra")]),
Pokemon(number: "066", name: "Machop", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/066.png")!, type: [.fighting], height: "0.79 m", weight: "19.5 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: [PokemonReference(number: "067", name: "Machoke"), PokemonReference(number: "068", name: "Machamp")], prev_evolution: nil),
Pokemon(number: "067", name: "Machoke", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/067.png")!, type: [.fighting], height: "1.50 m", weight: "70.5 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: [PokemonReference(number: "068", name: "Machamp")], prev_evolution: [PokemonReference(number: "066", name: "Machop")]),
Pokemon(number: "068", name: "Machamp", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/068.png")!, type: [.fighting], height: "1.60 m", weight: "130.0 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: nil, prev_evolution: [PokemonReference(number: "066", name: "Machop"), PokemonReference(number: "067", name: "Machoke")]),
Pokemon(number: "069", name: "Bellsprout", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/069.png")!, type: [.grass, .poison], height: "0.71 m", weight: "4.0 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "070", name: "Weepinbell"), PokemonReference(number: "071", name: "Victreebel")], prev_evolution: nil),
Pokemon(number: "070", name: "Weepinbell", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/070.png")!, type: [.grass, .poison], height: "0.99 m", weight: "6.4 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: [PokemonReference(number: "071", name: "Victreebel")], prev_evolution: [PokemonReference(number: "069", name: "Bellsprout")]),
Pokemon(number: "071", name: "Victreebel", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/071.png")!, type: [.grass, .poison], height: "1.70 m", weight: "15.5 kg", weaknesses: [.fire, .ice, .flying, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "069", name: "Bellsprout"), PokemonReference(number: "070", name: "Weepinbell")]),
Pokemon(number: "072", name: "Tentacool", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/072.png")!, type: [.water, .poison], height: "0.89 m", weight: "45.5 kg", weaknesses: [.electric, .ground, .psychic], next_evolution: [PokemonReference(number: "073", name: "Tentacruel")], prev_evolution: nil),
Pokemon(number: "073", name: "Tentacruel", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/073.png")!, type: [.water, .poison], height: "1.60 m", weight: "55.0 kg", weaknesses: [.electric, .ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "072", name: "Tentacool")]),
Pokemon(number: "074", name: "Geodude", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/074.png")!, type: [.rock, .ground], height: "0.41 m", weight: "20.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: [PokemonReference(number: "075", name: "Graveler"), PokemonReference(number: "076", name: "Golem")], prev_evolution: nil),
Pokemon(number: "075", name: "Graveler", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/075.png")!, type: [.rock, .ground], height: "0.99 m", weight: "105.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: [PokemonReference(number: "076", name: "Golem")], prev_evolution: [PokemonReference(number: "074", name: "Geodude")]),
Pokemon(number: "076", name: "Golem", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/076.png")!, type: [.rock, .ground], height: "1.40 m", weight: "300.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: nil, prev_evolution: [PokemonReference(number: "074", name: "Geodude"), PokemonReference(number: "075", name: "Graveler")]),
Pokemon(number: "077", name: "Ponyta", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/077.png")!, type: [.fire], height: "0.99 m", weight: "30.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: [PokemonReference(number: "078", name: "Rapidash")], prev_evolution: nil),
Pokemon(number: "078", name: "Rapidash", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/078.png")!, type: [.fire], height: "1.70 m", weight: "95.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "077", name: "Ponyta")]),
Pokemon(number: "079", name: "Slowpoke", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/079.png")!, type: [.water, .psychic], height: "1.19 m", weight: "36.0 kg", weaknesses: [.electric, .grass, .bug, .ghost, .dark], next_evolution: [PokemonReference(number: "080", name: "Slowbro")], prev_evolution: nil),
Pokemon(number: "080", name: "Slowbro", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/080.png")!, type: [.water, .psychic], height: "1.60 m", weight: "78.5 kg", weaknesses: [.electric, .grass, .bug, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "079", name: "Slowpoke")]),
Pokemon(number: "081", name: "Magnemite", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/081.png")!, type: [.electric], height: "0.30 m", weight: "6.0 kg", weaknesses: [.fire, .water, .ground], next_evolution: [PokemonReference(number: "082", name: "Magneton")], prev_evolution: nil),
Pokemon(number: "082", name: "Magneton", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/082.png")!, type: [.electric], height: "0.99 m", weight: "60.0 kg", weaknesses: [.fire, .water, .ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "081", name: "Magnemite")]),
Pokemon(number: "083", name: "Farfetch'd", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/083.png")!, type: [.normal, .flying], height: "0.79 m", weight: "15.0 kg", weaknesses: [.electric, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "084", name: "Doduo", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/084.png")!, type: [.normal, .flying], height: "1.40 m", weight: "39.2 kg", weaknesses: [.electric, .rock], next_evolution: [PokemonReference(number: "085", name: "Dodrio")], prev_evolution: nil),
Pokemon(number: "085", name: "Dodrio", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/085.png")!, type: [.normal, .flying], height: "1.80 m", weight: "85.2 kg", weaknesses: [.electric, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "084", name: "Doduo")]),
Pokemon(number: "086", name: "Seel", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/086.png")!, type: [.water], height: "1.09 m", weight: "90.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "087", name: "Dewgong")], prev_evolution: nil),
Pokemon(number: "087", name: "Dewgong", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/087.png")!, type: [.water, .ice], height: "1.70 m", weight: "120.0 kg", weaknesses: [.electric, .grass, .fighting, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "086", name: "Seel")]),
Pokemon(number: "088", name: "Grimer", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/088.png")!, type: [.poison], height: "0.89 m", weight: "30.0 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "089", name: "Muk")], prev_evolution: nil),
Pokemon(number: "089", name: "Muk", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/089.png")!, type: [.poison], height: "1.19 m", weight: "30.0 kg", weaknesses: [.ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "088", name: "Grimer")]),
Pokemon(number: "090", name: "Shellder", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/090.png")!, type: [.water], height: "0.30 m", weight: "4.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "091", name: "Cloyster")], prev_evolution: nil),
Pokemon(number: "091", name: "Cloyster", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/091.png")!, type: [.water, .ice], height: "1.50 m", weight: "132.5 kg", weaknesses: [.electric, .grass, .fighting, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "090", name: "Shellder")]),
Pokemon(number: "092", name: "Gastly", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/092.png")!, type: [.ghost, .poison], height: "1.30 m", weight: "0.1 kg", weaknesses: [.ground, .psychic, .ghost, .dark], next_evolution: [PokemonReference(number: "093", name: "Haunter"), PokemonReference(number: "094", name: "Gengar")], prev_evolution: nil),
Pokemon(number: "093", name: "Haunter", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/093.png")!, type: [.ghost, .poison], height: "1.60 m", weight: "0.1 kg", weaknesses: [.ground, .psychic, .ghost, .dark], next_evolution: [PokemonReference(number: "094", name: "Gengar")], prev_evolution: [PokemonReference(number: "092", name: "Gastly")]),
Pokemon(number: "094", name: "Gengar", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/094.png")!, type: [.ghost, .poison], height: "1.50 m", weight: "40.5 kg", weaknesses: [.ground, .psychic, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "092", name: "Gastly"), PokemonReference(number: "093", name: "Haunter")]),
Pokemon(number: "095", name: "Onix", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/095.png")!, type: [.rock, .ground], height: "8.79 m", weight: "210.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "096", name: "Drowzee", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/096.png")!, type: [.psychic], height: "0.99 m", weight: "32.4 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: [PokemonReference(number: "097", name: "Hypno")], prev_evolution: nil),
Pokemon(number: "097", name: "Hypno", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/097.png")!, type: [.psychic], height: "1.60 m", weight: "75.6 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "096", name: "Drowzee")]),
Pokemon(number: "098", name: "Krabby", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/098.png")!, type: [.water], height: "0.41 m", weight: "6.5 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "099", name: "Kingler")], prev_evolution: nil),
Pokemon(number: "099", name: "Kingler", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/099.png")!, type: [.water], height: "1.30 m", weight: "60.0 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "098", name: "Krabby")]),
Pokemon(number: "100", name: "Voltorb", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/100.png")!, type: [.electric], height: "0.51 m", weight: "10.4 kg", weaknesses: [.ground], next_evolution: [PokemonReference(number: "101", name: "Electrode")], prev_evolution: nil),
Pokemon(number: "101", name: "Electrode", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/101.png")!, type: [.electric], height: "1.19 m", weight: "66.6 kg", weaknesses: [.ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "100", name: "Voltorb")]),
Pokemon(number: "102", name: "Exeggcute", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/102.png")!, type: [.grass, .psychic], height: "0.41 m", weight: "2.5 kg", weaknesses: [.fire, .ice, .poison, .flying, .bug, .ghost, .dark], next_evolution: [PokemonReference(number: "103", name: "Exeggutor")], prev_evolution: nil),
Pokemon(number: "103", name: "Exeggutor", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/103.png")!, type: [.grass, .psychic], height: "2.01 m", weight: "120.0 kg", weaknesses: [.fire, .ice, .poison, .flying, .bug, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "102", name: "Exeggcute")]),
Pokemon(number: "104", name: "Cubone", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/104.png")!, type: [.ground], height: "0.41 m", weight: "6.5 kg", weaknesses: [.water, .grass, .ice], next_evolution: [PokemonReference(number: "105", name: "Marowak")], prev_evolution: nil),
Pokemon(number: "105", name: "Marowak", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/105.png")!, type: [.ground], height: "0.99 m", weight: "45.0 kg", weaknesses: [.water, .grass, .ice], next_evolution: nil, prev_evolution: [PokemonReference(number: "104", name: "Cubone")]),
Pokemon(number: "106", name: "Hitmonlee", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/106.png")!, type: [.fighting], height: "1.50 m", weight: "49.8 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "107", name: "Hitmonchan", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/107.png")!, type: [.fighting], height: "1.40 m", weight: "50.2 kg", weaknesses: [.flying, .psychic, .fairy], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "108", name: "Lickitung", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/108.png")!, type: [.normal], height: "1.19 m", weight: "65.5 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "109", name: "Koffing", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/109.png")!, type: [.poison], height: "0.61 m", weight: "1.0 kg", weaknesses: [.ground, .psychic], next_evolution: [PokemonReference(number: "110", name: "Weezing")], prev_evolution: nil),
Pokemon(number: "110", name: "Weezing", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/110.png")!, type: [.poison], height: "1.19 m", weight: "9.5 kg", weaknesses: [.ground, .psychic], next_evolution: nil, prev_evolution: [PokemonReference(number: "109", name: "Koffing")]),
Pokemon(number: "111", name: "Rhyhorn", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/111.png")!, type: [.ground, .rock], height: "0.99 m", weight: "115.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: [PokemonReference(number: "112", name: "Rhydon")], prev_evolution: nil),
Pokemon(number: "112", name: "Rhydon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/112.png")!, type: [.ground, .rock], height: "1.91 m", weight: "120.0 kg", weaknesses: [.water, .grass, .ice, .fighting, .ground, .steel], next_evolution: nil, prev_evolution: [PokemonReference(number: "111", name: "Rhyhorn")]),
Pokemon(number: "113", name: "Chansey", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/113.png")!, type: [.normal], height: "1.09 m", weight: "34.6 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "114", name: "Tangela", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/114.png")!, type: [.grass], height: "0.99 m", weight: "35.0 kg", weaknesses: [.fire, .ice, .poison, .flying, .bug], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "115", name: "Kangaskhan", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/115.png")!, type: [.normal], height: "2.21 m", weight: "80.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "116", name: "Horsea", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/116.png")!, type: [.water], height: "0.41 m", weight: "8.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "117", name: "Seadra")], prev_evolution: nil),
Pokemon(number: "117", name: "Seadra", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/117.png")!, type: [.water], height: "1.19 m", weight: "25.0 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "116", name: "Horsea")]),
Pokemon(number: "118", name: "Goldeen", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/118.png")!, type: [.water], height: "0.61 m", weight: "15.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "119", name: "Seaking")], prev_evolution: nil),
Pokemon(number: "119", name: "Seaking", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/119.png")!, type: [.water], height: "1.30 m", weight: "39.0 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "118", name: "Goldeen")]),
Pokemon(number: "120", name: "Staryu", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/120.png")!, type: [.water], height: "0.79 m", weight: "34.5 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "121", name: "Starmie")], prev_evolution: nil),
Pokemon(number: "121", name: "Starmie", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/121.png")!, type: [.water, .psychic], height: "1.09 m", weight: "80.0 kg", weaknesses: [.electric, .grass, .bug, .ghost, .dark], next_evolution: nil, prev_evolution: [PokemonReference(number: "120", name: "Staryu")]),
Pokemon(number: "122", name: "Mr. Mime", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/122.png")!, type: [.psychic], height: "1.30 m", weight: "54.5 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "123", name: "Scyther", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/123.png")!, type: [.bug, .flying], height: "1.50 m", weight: "56.0 kg", weaknesses: [.fire, .electric, .ice, .flying, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "124", name: "Jynx", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/124.png")!, type: [.ice, .psychic], height: "1.40 m", weight: "40.6 kg", weaknesses: [.fire, .bug, .rock, .ghost, .dark, .steel], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "125", name: "Electabuzz", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/125.png")!, type: [.electric], height: "1.09 m", weight: "30.0 kg", weaknesses: [.ground], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "126", name: "Magmar", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/126.png")!, type: [.fire], height: "1.30 m", weight: "44.5 kg", weaknesses: [.water, .ground, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "127", name: "Pinsir", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/127.png")!, type: [.bug], height: "1.50 m", weight: "55.0 kg", weaknesses: [.fire, .flying, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "128", name: "Tauros", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/128.png")!, type: [.normal], height: "1.40 m", weight: "88.4 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "129", name: "Magikarp", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/129.png")!, type: [.water], height: "0.89 m", weight: "10.0 kg", weaknesses: [.electric, .grass], next_evolution: [PokemonReference(number: "130", name: "Gyarados")], prev_evolution: nil),
Pokemon(number: "130", name: "Gyarados", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/130.png")!, type: [.water, .flying], height: "6.50 m", weight: "235.0 kg", weaknesses: [.electric, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "129", name: "Magikarp")]),
Pokemon(number: "131", name: "Lapras", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/131.png")!, type: [.water, .ice], height: "2.49 m", weight: "220.0 kg", weaknesses: [.electric, .grass, .fighting, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "132", name: "Ditto", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/132.png")!, type: [.normal], height: "0.30 m", weight: "4.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "133", name: "Eevee", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/133.png")!, type: [.normal], height: "0.30 m", weight: "6.5 kg", weaknesses: [.fighting], next_evolution: [PokemonReference(number: "134", name: "Vaporeon"), PokemonReference(number: "135", name: "Jolteon"), PokemonReference(number: "136", name: "Flareon")], prev_evolution: nil),
Pokemon(number: "134", name: "Vaporeon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/134.png")!, type: [.water], height: "0.99 m", weight: "29.0 kg", weaknesses: [.electric, .grass], next_evolution: nil, prev_evolution: [PokemonReference(number: "133", name: "Eevee")]),
Pokemon(number: "135", name: "Jolteon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/135.png")!, type: [.electric], height: "0.79 m", weight: "24.5 kg", weaknesses: [.ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "133", name: "Eevee")]),
Pokemon(number: "136", name: "Flareon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/136.png")!, type: [.fire], height: "0.89 m", weight: "25.0 kg", weaknesses: [.water, .ground, .rock], next_evolution: nil, prev_evolution: [PokemonReference(number: "133", name: "Eevee")]),
Pokemon(number: "137", name: "Porygon", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/137.png")!, type: [.normal], height: "0.79 m", weight: "36.5 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "138", name: "Omanyte", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/138.png")!, type: [.rock, .water], height: "0.41 m", weight: "7.5 kg", weaknesses: [.electric, .grass, .fighting, .ground], next_evolution: [PokemonReference(number: "139", name: "Omastar")], prev_evolution: nil),
Pokemon(number: "139", name: "Omastar", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/139.png")!, type: [.rock, .water], height: "0.99 m", weight: "35.0 kg", weaknesses: [.electric, .grass, .fighting, .ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "138", name: "Omanyte")]),
Pokemon(number: "140", name: "Kabuto", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/140.png")!, type: [.rock, .water], height: "0.51 m", weight: "11.5 kg", weaknesses: [.electric, .grass, .fighting, .ground], next_evolution: [PokemonReference(number: "141", name: "Kabutops")], prev_evolution: nil),
Pokemon(number: "141", name: "Kabutops", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/141.png")!, type: [.rock, .water], height: "1.30 m", weight: "40.5 kg", weaknesses: [.electric, .grass, .fighting, .ground], next_evolution: nil, prev_evolution: [PokemonReference(number: "140", name: "Kabuto")]),
Pokemon(number: "142", name: "Aerodactyl", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/142.png")!, type: [.rock, .flying], height: "1.80 m", weight: "59.0 kg", weaknesses: [.water, .electric, .ice, .rock, .steel], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "143", name: "Snorlax", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/143.png")!, type: [.normal], height: "2.11 m", weight: "460.0 kg", weaknesses: [.fighting], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "144", name: "Articuno", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/144.png")!, type: [.ice, .flying], height: "1.70 m", weight: "55.4 kg", weaknesses: [.fire, .electric, .rock, .steel], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "145", name: "Zapdos", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/145.png")!, type: [.electric, .flying], height: "1.60 m", weight: "52.6 kg", weaknesses: [.ice, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "146", name: "Moltres", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/146.png")!, type: [.fire, .flying], height: "2.01 m", weight: "60.0 kg", weaknesses: [.water, .electric, .rock], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "147", name: "Dratini", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/147.png")!, type: [.dragon], height: "1.80 m", weight: "3.3 kg", weaknesses: [.ice, .dragon, .fairy], next_evolution: [PokemonReference(number: "148", name: "dragonair"), PokemonReference(number: "149", name: "dragonite")], prev_evolution: nil),
Pokemon(number: "148", name: "dragonair", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/148.png")!, type: [.dragon], height: "3.99 m", weight: "16.5 kg", weaknesses: [.ice, .dragon, .fairy], next_evolution: [PokemonReference(number: "149", name: "dragonite")], prev_evolution: [PokemonReference(number: "147", name: "Dratini")]),
Pokemon(number: "149", name: "dragonite", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/149.png")!, type: [.dragon, .flying], height: "2.21 m", weight: "210.0 kg", weaknesses: [.ice, .rock, .dragon, .fairy], next_evolution: nil, prev_evolution: [PokemonReference(number: "147", name: "Dratini"), PokemonReference(number: "148", name: "dragonair")]),
Pokemon(number: "150", name: "Mewtwo", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/150.png")!, type: [.psychic], height: "2.01 m", weight: "122.0 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: nil, prev_evolution: nil),
Pokemon(number: "151", name: "Mew", image: URL(string: "https://www.serebii.net/pokemongo/pokemon/151.png")!, type: [.psychic], height: "0.41 m", weight: "4.0 kg", weaknesses: [.bug, .ghost, .dark], next_evolution: nil, prev_evolution: nil)
]
